### ISSUE TITLE
Can’t select AIR_CONDITIONING as zone’s mode

### ISSUE THREAD

**Issue by badgertastic** [SeydX/homebridge-tado-platform#173]
### Analysis

Hi. Are you meant to be able to select AIR_CONDITIONING as zone’s mode in config UI? Only heating and hot water are available. 
Is the Tado Smart AC control device supported?
I added it manually as mode AIR_CONDITIONING in config json but the API just errors when trying to control. 
Does Tado Smart AC control need a zone ID? How to find fhe zone ID please?

Thanks

### Expected Behavior

Able to control Tado smart AC control device

### Steps To Reproduce

See above

### Logs

```markdown
….request failed…
```

### Configuration

```json
See above
```

### Environment

- OS:
- Software:
- Node:
- npm:

### Process Supervisor

hb-service

**Comment by smart7324** [comment]
It seems that we are not fully supporting tado air conditioning. The whole implementation was a pull request that has been merged. It seems that there is still functionality missing, but please do understand, that this is a new feature requested and we need somebody who has enough spare time to implement and test these things.

**Comment by badgertastic** [comment]
Understand thanks. I was looking at alternative plugins but those say this one implemented it and they looked to have abandoned efforts since the api authentication changes. 

I’m hopeful to get more feature rich control of the AC (fan level, swivel… etc) in future direct from HomeKit but at least I have Tado app for this in meantime. Ciao

**Comment by smart7324** [comment]
Fixed in 8.7.0.

**Comment by badgertastic** [comment]
Same errors. I found my zone id after lots of faffing with Postman and keys. Zone id it needs otherwise api url shows as ‘undefined’ but api still throws code 422 Unprocessible Entity. 

Minstep shows as undefined too, so also looks like should be mandatory field.

**Comment by smart7324** [comment]
@badgertastic I see. You only posted the error `….request failed…` so I assumed it was the same error like in #170 `HTTP Status: 422 - Response: {"errors":[{"code":"validator.invalid","title":"Property [termination.typeSkillBasedApp] of class [class com.tado.publicapi.OverlayTerminationConditionCommand] with value [null] does not pass custom validation"}]}`. This error is now fixed.

You can now also select `AIR_CONDITIONING` in the config UI.

I'll reopen your issue.

**Comment by badgertastic** [comment]
Thanks and sorry i was being lazy about the log errors (on iPad and hard to cut/paste/redactions)…


```
[11/3/2025, 7:00:17 PM] [TadoPlatform] redacted Air Conditioning AC: Configuring accessory...
Before MINSTEP: undefined redacted Air Conditioning AC
After MINSTEP: 1 redacted Air Conditioning AC
[11/3/2025, 7:00:17 PM] Homebridge v1.11.1 (HAP v0.14.0) (TadoPlatform) is running on port 35568.
[11/3/2025, 7:00:21 PM] [TadoPlatform] Tado API counter: 107
[11/3/2025, 7:00:40 PM] [TadoPlatform] redacted Air Conditioning AC: Temperature: 20
[11/3/2025, 7:00:40 PM] [TadoPlatform] redacted: API Request [PUT /api/v2/homes/redacted/zones/19/overlay] - FAILED: Request failed with status code 422 (Unprocessable Entity): PUT https://my.tado.com/api/v2/homes/redacted/zones/19/overlay
[11/3/2025, 7:00:40 PM] [TadoPlatform] Failed to set states: Request failed with status code 422 (Unprocessable Entity): PUT https://my.tado.com/api/v2/homes/redacted/zones/19/overlay
```

Zone id 19 I added to config otherwise shows ‘undefined’ above.

**Comment by smart7324** [comment]
@badgertastic thanks for your patience!

Could you please try to reconfigure the AC again on `v9.2.0`?

Also I'd like to investigate the 422 error further. Could you please enable debug logging and share the output?

Add "debug": true to your config:
```json
{
  "platforms": [{
    "platform": "TadoPlatform",
    "debug": true,
    ...
  }]
}
```

After restarting Homebridge, trigger the issue again and share the full log output – especially the API request start and API request failed lines for the /overlay call. Thanks!

**Comment by badgertastic** [comment]
I added air con back a few days ago and not seeing any errors currently. 9.1.2

**Comment by smart7324** [comment]
Perfect! So I am closing this as completed.
