### ISSUE TITLE
overrideMode only works as "manual" for HOT_WATER

### ISSUE THREAD

**Issue by omarassil** [SeydX/homebridge-tado-platform#27]
Hi,
I tried to set the "overrideMode": "manual", to a different value in the HOT_WATER device options but it's not working. It's always turning it on/off and setting the overlay option to manual (until changed by the user). I tried many values(auto, null, false, 0) but none of them worked. Could you please check and

**Comment by SeydX** [comment]
Fixed in v6

**Comment by omarassil** [comment]
Hi @SeydX  I'm still having issues with hot-water with the new plugin. let me summarise:
- When hot-water is on in Tado, turning it off in HomeKit is resulting in it being off in Tado but "until you cancel" so it's not respecting the auto mode although I selected AUTO in my homebridge config
- When hot-water is off in Tado, turning it on in HomeKit will do nothing. After the polling duration it will go toggle back to off in HomeKit automatically

**Comment by SeydX** [comment]
Currently there is no real auto mode for hot water implemented due to some reasons. Will fix this

**Comment by SeydX** [comment]
Fixed in v6.0.9

**Comment by omarassil** [comment]
Hi @SeydX , I still have the issues. I summarised the various states:
- Tado app Hot Water OFF as per auto schedule -> turning ON in HomeKit will do nothing -> HomeKit reverts back to OFF state after 30 sec X
- Tado app Hot Water OFF manually (while schedule is ON) -> turning ON in HomeKit will do nothing -> HomeKit reverts back to OFF states after 30 sec X
- Tado app Hot Water ON manually (while schedule is OFF) -> turning OFF in HomeKit will turn it off in Tado √
- Tado app Hot Water ON as per auto schedule -> turning OFF in HomeKit will turn it off in Tado √
